# Generated by Django 6.0.3 on 2026-03-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='clicks_count',
            field=models.IntegerField(default=0, help_text='Сколько раз кликнули по ссылке (обновляется автоматически).', verbose_name='Клики'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Для графиков или рекламных картинок.', null=True, upload_to='banners/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть баннер с сайта.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название (только для админки)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше в колонке.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('left', 'Левая колонка - аналитика'), ('right', 'Правая колонка - реклама')], default='right', help_text='Слева — аналитика (графики, статистика). Справа — реклама или ссылки.', max_length=20, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.TextField(blank=True, help_text='Необязательно. Описание под заголовком (или отдельно, если заголовка нет).', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text='Необязательно. Если есть картинка — будет под ней.', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, help_text="Куда перейдёт пользователь при клике на баннер или кнопку 'Подробнее'.", verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Сколько раз баннер показан пользователям (обновляется автоматически).', verbose_name='Показы'),
        ),
    ]
