# Generated by Django 6.0.3 on 2026-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_clicks_count_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('left', 'Левая колонка - аналитика'), ('right', 'Правая колонка - реклама'), ('center_top', 'Центральная колонка - первая новость')], default='right', help_text='Слева — аналитика (графики, статистика). Справа — реклама или ссылки.', max_length=20, verbose_name='Позиция'),
        ),
    ]
