# Generated by Django 6.0.3 on 2026-03-10 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID сообщения в TG')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('preview', models.TextField(blank=True, max_length=300, verbose_name='Превью (кратко)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Изображение')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено на сайт')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('reactions', models.JSONField(blank=True, default=dict, verbose_name='Реакции (эмодзи)')),
                ('slug', models.SlugField(blank=True, help_text='Будет автоматически сгенерирован из заголовка, если не заполнен', max_length=200, unique=True, verbose_name='ЧПУ (slug)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (если пусто = заголовок)')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='Meta Keywords (через запятую)')),
                ('h1_title', models.CharField(blank=True, max_length=200, verbose_name='H1 заголовок (если пусто = заголовок)')),
                ('is_index', models.BooleanField(default=True, verbose_name='Разрешить индексацию')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
