# Generated by Django 6.0.3 on 2026-03-10 16:36

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='h1_title',
            field=models.CharField(blank=True, help_text='Заголовок на странице новости. Если не заполнить — будет использован обычный заголовок. Пример: «Итоги рынка апартаментов за февраль 2026»', max_length=200, verbose_name='H1 заголовок (если пусто = заголовок)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_index',
            field=models.BooleanField(default=True, help_text='Если снять галочку — страница будет закрыта от индексации (noindex). Обычно оставляем включенным.', verbose_name='Разрешить индексацию'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Краткое описание (150-200 символов) — показывается в поиске под заголовком. Если не заполнить — поисковик сам возьмет кусок текста. Пример: «Аналитика рынка апартаментов: средняя цена, спрос, новые ЖК. Данные по Москве и СПб за февраль 2026.»', max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую. Пример: «апартаменты, рынок недвижимости, аналитика, новостройки, инвестиции»', max_length=250, verbose_name='Meta Keywords (через запятую)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок для поисковых систем (то, что видно в выдаче). Если не заполнить — возьмется из обычного заголовка. Пример: «Итоги рынка апартаментов за февраль 2026 | apartprofi»', max_length=200, verbose_name='Meta Title (если пусто = заголовок)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.TextField(blank=True, help_text='Если оставить пустым, автоматически возьмутся первые 200 символов из текста новости', max_length=300, verbose_name='Превью (кратко)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Часть URL после /news/. Если не заполнить — создастся автоматически из заголовка. Пример: «itogi-rynka-fevral-2026»', max_length=200, unique=True, verbose_name='ЧПУ (slug)'),
        ),
    ]
