# Generated by Django 6.0.3 on 2026-03-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_thumbnail_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Автоматически сжимается и создаётся миниатюра для ленты.', null=True, upload_to='news/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть новость с сайта.', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.TextField(blank=True, help_text='Если оставить пустым, в ленте покажутся первые 200 символов текста.', max_length=300, verbose_name='Превью (кратко)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок новости'),
        ),
    ]
