# Generated by Django 6.0.3 on 2026-03-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image_alter_news_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, help_text='Файл для скачивания (необязательно)', null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='Вложение (PDF, таблица и т.д.)'),
        ),
    ]
