# Generated by Django 6.0.3 on 2026-03-23 14:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=tinymce.models.HTMLField(blank=True, help_text='Если оставить пустым, в ленте покажутся первые 200 символов текста.', max_length=300, verbose_name='Превью (кратко)'),
        ),
    ]
