# Generated by Django 6.0.3 on 2026-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Например: фото: Иван Иванов, источник: unsplash.com', max_length=200, verbose_name='Автор / источник'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='Если указана, ссылка появится под картинкой', max_length=500, verbose_name='Ссылка на источник'),
        ),
    ]
