# Generated by Django 6.0.3 on 2026-03-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_image_credit_news_image_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='credit',
            field=models.CharField(blank=True, help_text='Например: фото: Иван Иванов', max_length=200, verbose_name='Автор / источник'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на источник'),
        ),
    ]
