# Generated by Django 6.0.3 on 2026-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_newsimage_credit_newsimage_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы выделить жирным справа.', verbose_name='Важный заголовок (жирный в правой колонке)'),
        ),
    ]
