# Generated by Django 6.0.3 on 2026-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='comments_enabled',
            field=models.BooleanField(default=True, verbose_name='Комментарии включены'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='headlines_count',
            field=models.IntegerField(default=15, verbose_name='Количество заголовков в правой колонке'),
        ),
    ]
