# Generated by Django 6.0.3 on 2026-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка (опционально)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Элемент бегущей строки',
                'verbose_name_plural': 'Элементы бегущей строки',
                'ordering': ['order'],
            },
        ),
    ]
