# Generated by Django 6.0.3 on 2026-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_ticker_delete_tickeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='speed',
            field=models.IntegerField(default=60, help_text='Чем меньше число, тем быстрее бежит строка', verbose_name='Скорость (секунды)'),
        ),
    ]
